apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: frontend
    repoURL: https://github.com/Grahnkoul/ArgoCD
    targetRevision: main
  syncPolicy:
    automated: {}
